DROP TABLE IF EXISTS `pokemon` CASCADE;

CREATE TABLE pokemon (
id long AUTO_INCREMENT,
ndex VARCHAR(10) NOT NULL UNIQUE,
name VARCHAR(100) NOT NULL,
type VARCHAR(100) NOT NULL,
gender VARCHAR(100) NOT NULL,
height FLOAT NOT NULL,
weight FLOAT NOT NULL,
bst INT NOT NULL,
PRIMARY KEY (id)
);